---
title: "Getting start: scHOT"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Getting start: scHOT}
  %\usepackage[UTF-8]{inputenc}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = "#>"
)
```



```{r}
library(SingleCellExperiment)
library(scHOT)
```


# Trajectory data: liver

```{r}
load("../data/liver.Rda", verbose = TRUE)
```


```{r}
n_first = length(intersect(colnames(liver_branch_chol), colnames(liver_branch_hep)))

gene_to_test <- cbind(c("Birc5", "H2afz", "Tacc3"),
                      c("Birc5", "H2afz", "Tacc3"))

weightedVar2 <- function(x, y, w) {
  weightedVar2 <- weightedVar(x, w)
}
```

## Hepatocytes branch

```{r}
scHOT_trajectory_hepatocytes <- scHOT_buildFromMatrix(mat = liver_branch_hep,
                                                      cellData = list(pseudotime = liver_pseudotime_hep),
                                                      positionType = "trajectory",
                                                      positionColData = "pseudotime")


scHOT_trajectory_hepatocytes <- scHOT_addTestingScaffold(scHOT_trajectory_hepatocytes, gene_to_test)

scHOT_trajectory_hepatocytes <- scHOT_setWeightMatrix(scHOT_trajectory_hepatocytes,
                                                      positionColData = c("pseudotime"),
                                                      positionType = "trajectory",
                                                      nrow.out = NULL,
                                                      span = 0.5*n_first/ncol(liver_branch_hep))


scHOT_trajectory_hepatocytes <- scHOT_calculateGlobalHigherOrderFunction(scHOT_trajectory_hepatocytes, 
                                                                         higherOrderFunction = weightedVar2,
                                                                         higherOrderFunctionType = "weighted")


scHOT_trajectory_hepatocytes@scHOT_output

scHOT_trajectory_hepatocytes <- scHOT_setPermutationScaffold(scHOT_trajectory_hepatocytes, 
                                                             numberPermutations = 100)


scHOT_trajectory_hepatocytes@scHOT_output


scHOT_trajectory_hepatocytes <- scHOT_calculateHigherOrderTestStatistics(scHOT_trajectory_hepatocytes,
                                                                         higherOrderSummaryFunction = sd)

scHOT_trajectory_hepatocytes@scHOT_output




system.time(scHOT_trajectory_hepatocytes <- scHOT_performPermutationTest(scHOT_trajectory_hepatocytes, 
                                                                         verbose = TRUE,
                                                                         parallel = TRUE,
                                                                         BPPARAM = MulticoreParam(workers = 4)))





scHOT_trajectory_hepatocytes <- scHOT_estimatePvalues(scHOT_trajectory_hepatocytes)
scHOT_trajectory_hepatocytes@scHOT_output

scHOT_trajectory_hepatocytes@scHOT_output$higherOrderSequence

plotHigherOrderSequence(scHOT_trajectory_hepatocytes, "Tacc3")
```



## Branch: Cholangiocytes

Perform similar analysis using `scHOT` wrap up function for the cholangiocytes branch

```{r}


scHOT_trajectory_cholangiocytes <- scHOT_buildFromMatrix(mat = liver_branch_chol,
                                                         cellData = list(pseudotime = liver_pseudotime_chol),
                                                         positionType = "trajectory",
                                                         positionColData = "pseudotime")


scHOT_trajectory_cholangiocytes <- scHOT(scHOT_trajectory_cholangiocytes,
                       testingScaffold = matrix(c("Tacc3", "Tacc3"), 
                                                ncol = 2, byrow = TRUE),
                       positionType = "trajectory",
                       positionColData = c("pseudotime"),
                       nrow.out = NULL,
                       higherOrderFunction = weightedVar2,
                       higherOrderFunctionType = 'weighted',
                       numberPermutations = 100,
                       higherOrderSummaryFunction = sd,
                       parallel = TRUE,
                       BPPARAM = MulticoreParam(workers = 4),
                       verbose = TRUE,
                       span = 0.5*n_first/ncol(liver_branch_chol))

plotHigherOrderSequence(scHOT_trajectory_cholangiocytes, "Tacc3")


```





# Spatial data: MOB

## Perform scHOT step by step

```{r}
load("../data/MOB_subset.Rda", verbose = TRUE)
sce_MOB_subset


scHOT_spatial <- scHOT_buildFromSCE(sce_MOB_subset,
                                    assayName = "counts",
                                    positionType = "spatial",
                                    positionColData = c("x", "y"))
```




```{r}

scHOT_spatial <- scHOT_buildFromSCE(sce_MOB_subset,
                                    assayName = "counts",
                                    positionType = "spatial",
                                    positionColData = c("x", "y"))
logcounts(scHOT_spatial) <- logcounts(sce_MOB_subset)



pairs <- t(combn(intersect(HVG, nonDEgenes),2))
rownames(pairs) <- apply(pairs,1,paste0,collapse = "_")



set.seed(2020)
pairs <- pairs[sample(nrow(pairs), 10), ]

cat("Pairs to be tested")
pairs <- rbind(pairs, c("Arrb1", "Mtor"))

scHOT_spatial <- scHOT_addTestingScaffold(scHOT_spatial, pairs)

scHOT_spatial <- scHOT_setWeightMatrix(scHOT_spatial,
                                       positionColData = c("x","y"),
                                       positionType = "spatial",
                                       nrow.out = NULL,
                                       span = 0.05)

dim(scHOT_spatial@weightMatrix)

scHOT_spatial <- scHOT_calculateGlobalHigherOrderFunction(scHOT_spatial, 
                                                          higherOrderFunction = weightedSpearman,
                                                          higherOrderFunctionType = "weighted")


scHOT_spatial@scHOT_output

scHOT_spatial <- scHOT_setPermutationScaffold(scHOT_spatial, 
                                              numberPermutations = 100)


scHOT_spatial@scHOT_output


scHOT_spatial <- scHOT_calculateHigherOrderTestStatistics(scHOT_spatial,
                                                          higherOrderSummaryFunction = sd)

scHOT_spatial@scHOT_output




system.time(scHOT_spatial <- scHOT_performPermutationTest(scHOT_spatial, 
                                                          verbose = TRUE,
                                                          parallel = TRUE,
                                                          BPPARAM = MulticoreParam(workers = 4)))





scHOT_spatial <- scHOT_estimatePvalues(scHOT_spatial)
scHOT_spatial@scHOT_output

colData(scHOT_spatial)[, "-x"] <- -colData(scHOT_spatial)[, "x"]
plotHigherOrderSequence(scHOT_spatial, c("Dnm1l_Gucy1b3"),
                        positionColData = c("-x", "y"))

plotOrderedExpression(scHOT_spatial, "Dnm1l_Gucy1b3",
                      positionColData = c("-x", "y"),
                      assayName = "logcounts")


```

## Perform scHOT using `scHOT` wrap-up function

Please strip the scHOT output using `scHOT_stripOutput` before rerun scHOT. 
```{r}
scHOT_spatial <- scHOT_stripOutput(scHOT_spatial, force = TRUE)
```


```{r}
scHOT_spatial <- scHOT(scHOT_spatial,
                       testingScaffold = matrix(c("Arrb1", "Mtor"), 
                                                ncol = 2, byrow = TRUE),
                       positionType = "spatial",
                       positionColData = c("x", "y"),
                       nrow.out = NULL,
                       higherOrderFunction = weightedSpearman,
                       higherOrderFunctionType = 'weighted',
                       numberPermutations = 100,
                       higherOrderSummaryFunction = sd,
                       parallel = TRUE,
                       BPPARAM = MulticoreParam(workers = 4),
                       verbose = TRUE,
                       span = 0.05)



plotOrderedExpression(scHOT_spatial, "Arrb1_Mtor",
                      positionColData = c("-x", "y"),
                      assayName = "logcounts")
plotHigherOrderSequence(scHOT_spatial, "Arrb1_Mtor",
                        positionColData = c("-x", "y"))

```




```{r}
sessionInfo()
```
